# SPDX-License-Identifier: MIT
# OpenTina minimal CLI distribution
#
# Headless serial-console system with networking and OpenSSH.

require conf/distro/poky.conf
require conf/include/opentina-default-users.inc

DISTRO = "opentina-minimal"
DISTRO_NAME = "OpenTina Minimal"
DISTROOVERRIDES = "opentina:opentina-minimal"
TCLIBC = "glibc"

DISTRO_FEATURES:append = " ipv4 usbhost wifi"

PREFERRED_VERSION_linux-yocto ?= "6.10%"

# Rootfs-only until Allwinner BSP kernel is integrated
PREFERRED_PROVIDER_virtual/kernel:opentina-minimal ?= "linux-dummy"
