# SPDX-License-Identifier: MIT
require conf/distro/poky.conf
require conf/include/opentina-default-users.inc

DISTRO = "opentina-hmi"
DISTRO_NAME = "OpenTina HMI"
DISTROOVERRIDES = "opentina:opentina-hmi"
TCLIBC = "glibc"

# Wayland/Weston HMI stack: opengl+egl for Mesa (software-rendered swrast/
# llvmpipe until an A733 GPU/DRM driver lands), x11 for XWayland, pulseaudio
# for audio. systemd for service management.
DISTRO_FEATURES:append = " opengl egl wayland x11 pulseaudio pam systemd"

PREFERRED_VERSION_linux-yocto ?= "6.10%"
PREFERRED_PROVIDER_virtual/kernel:opentina-hmi ?= "linux-dummy"
